// Nano Banana Pro — highest quality Gemini image model
const GEMINI_MODEL = 'gemini-3-pro-image-preview'
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`

interface GeminiPart {
  text?: string
  inlineData?: {
    mimeType: string
    data: string // base64
  }
}

interface GeminiResponse {
  candidates?: Array<{
    content: {
      parts: GeminiPart[]
    }
  }>
  error?: { message: string }
}

interface GenerateImageOptions {
  aspectRatio?: string
  imageSize?: '1K' | '2K' | '4K'
}

export async function generateImage(
  prompt: string,
  options: GenerateImageOptions = {}
): Promise<Buffer> {
  const apiKey = process.env.GOOGLE_GEMINI_API_KEY
  if (!apiKey) {
    throw new Error('GOOGLE_GEMINI_API_KEY is not set')
  }

  const { aspectRatio = '1:1', imageSize = '1K' } = options

  const res = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
        imageConfig: {
          aspectRatio,
          imageSize,
        },
      },
    }),
  })

  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Gemini API error (${res.status}): ${errText}`)
  }

  const data: GeminiResponse = await res.json()

  if (data.error) {
    throw new Error(`Gemini API error: ${data.error.message}`)
  }

  const parts = data.candidates?.[0]?.content?.parts
  if (!parts) {
    throw new Error('No content in Gemini response')
  }

  // Find the image part
  const imagePart = parts.find(p => p.inlineData?.mimeType?.startsWith('image/'))
  if (!imagePart?.inlineData) {
    throw new Error('No image generated by Gemini')
  }

  return Buffer.from(imagePart.inlineData.data, 'base64')
}
