/**
 * Three coach fixtures designed to stress different hallucination patterns:
 *
 * 1. `fitness-sparse`  — mirrors Schad's April 15 case (sparse numeric input → math hallucinations)
 * 2. `business-abstract` — mirrors March 27 case (abstract niche → generic-metaphor hallucinations)
 * 3. `relationship-dense` — dense input → tests false-positive rate of the scanner
 *
 * Each fixture follows the full questionnaire schema (7 steps, all required fields).
 */

interface CoachFixture {
  id: string
  label: string
  niche: string
  answers: Record<string, unknown>
}

export const COACH_FIXTURES: CoachFixture[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // 1. FITNESS COACH — SPARSE INPUT (mirrors Schad Gibbons, April 15)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'fitness-sparse',
    label: 'Marcus Reed — Fitness Coach (sparse input)',
    niche: 'in-home fitness coaching for busy executives',
    answers: {
      // Step 1: Who You Are
      clientName: 'Marcus Reed',
      businessName: 'Reed Performance',
      elevatorPitch: 'I help busy executives get in the best shape of their lives without leaving their home office.',
      coachingYears: '11 years of personal training',
      totalClientsCoached: '340 clients',
      businessesBuiltList: 'Ran a single-location gym in Austin from 2015 to 2022.',
      positionsHeld: '',
      certifications: 'NASM CPT, Precision Nutrition L1',
      mediaAndStages: '',
      notableAssociations: '',
      twelveMonthVision: 'Grow to 50 paying clients in my coaching program by end of year.',

      // Step 2: Your Story
      upbringing: 'Raised in Ohio by a single mom who worked two jobs.',
      parentInfluence: 'Mom modeled relentless work ethic.',
      coachingLineage: '',
      firstBusiness: 'Personal training clients at a local Gold\'s Gym',
      storyBeforeState: 'In 2021 I was training 12 hours a day at my gym and still barely breaking even after lease and payroll. I was burnt out, gaining weight, and resenting clients.',
      storyTurningPoint: 'A client asked if I could train him over Zoom during COVID. I said yes, and realized I could help just as many people without a physical location.',
      storyAfterState: 'I closed the gym in 2022 and went fully online. I now coach executives remotely with customized home programs.',
      whyDoThis: 'Because I was the fat kid nobody believed in, and now I help people who\'ve given up on themselves prove their own critics wrong.',
      personalHobbies: ['running', 'reading', 'barbecue'],
      personalLife: 'Married, two kids, lives in Austin TX.',
      storyFacts: 'Started training in 2013. Opened Reed Performance gym 2015. Closed gym 2022. Went fully online 2022. 340 total clients coached. 11 years experience total.',

      // Step 3: Ideal Client
      niche: 'In-home fitness coaching for busy executives',
      targetAudience: 'Male executives age 40-55 who run their own companies, make $300K+, and haven\'t prioritized their health in years.',
      bestClientEver: 'CEO of a SaaS company, lost 42 pounds in 6 months while training from his home office.',
      topComplaints: 'No time. Previous trainers didn\'t understand their schedule.',
      unwantedFeelings: 'Embarrassed when they catch their reflection. Exhausted by 3pm. Dreading their next physical.',
      topDesires: 'Feel strong again. Be present for their kids. Stop avoiding photos.',
      desiredFeelings: 'Confident, capable, energetic, proud of how they look.',
      idealClientCurrentMethods: 'They buy Peloton bikes, hire local trainers they cancel on, download MyFitnessPal and abandon it after 2 weeks.',
      whyCurrentMethodFails: 'Generic programs. No accountability. Don\'t account for business travel or 60-hour weeks.',
      aspiringIdentity: 'The executive athlete — a high performer who takes his body as seriously as his P&L.',
      problemSolved: 'Executives who can\'t fit conventional fitness into their schedule and have tried 3+ approaches without lasting results.',
      commonObjections: [
        'I don\'t have time to train',
        'Online coaching can\'t replace in-person',
        'I\'ve tried this before and it didn\'t stick',
      ],
      salesApproach: 'application-call',
      deliveryModel: '1-on-1',
      idealClientCurrentRevenue: '$500K-$5M company revenue',
      idealClientStuckDuration: '3-5 years stuck',
      monthlyActionCost: 'Every month of delay = another month closer to the heart attack his father had at 58. Plus ~$500/month wasted on unused Peloton memberships and canceled trainers.',

      // Step 4: Deep Psychology
      clientExcuse: 'I\'ll start after this quarter ends.',
      clientSecretDesire: 'To take off his shirt at the beach without sucking in.',
      clientFalseProblem: 'I just need more willpower.',
      clientRealProblem: 'No system that fits the reality of a 60-hour work week.',
      clientSecretFear: 'Dying young like his father did at 58.',
      clientAngerTrigger: 'Watching his younger VP out-lift him at the company retreat.',
      clientBlameTarget: 'Every trainer who gave him a cookie-cutter program.',
      clientGuiltShame: 'Skipping his son\'s baseball games because he was too tired.',
      clientDailyReminder: 'Catching his reflection in the elevator mirror each morning.',
      clientInactionConsequence: 'A heart attack before 55. Missing his daughter\'s wedding.',

      // Step 5: Program
      offerName: 'The Executive Athlete Program',
      programPhases: [
        { phaseName: 'Assessment', description: '3 video calls + bloodwork review', outcome: 'Custom baseline' },
        { phaseName: 'Rebuild', description: '8 weeks of in-home strength + nutrition protocol', outcome: 'First 15-20 lb loss + strength baseline' },
        { phaseName: 'Scale', description: '12 weeks of progressive loading + travel protocols', outcome: 'Transformation + maintenance system' },
      ],
      doneForYou: 'Custom program, weekly video reviews, biweekly 1-on-1 calls.',
      taughtSkills: 'Nutrition in a business-travel context. Training through jet lag. How to use hotel gyms.',
      billboardResult: 'Lose 30 lbs in 6 months without missing a single business meeting.',
      bonuses: 'Private Slack access, quarterly bloodwork review.',
      clientCapacity: '12 active clients at a time',
      pricing: {
        totalUSD: 12000,
        billingType: 'installments' as const,
        displayString: '$12,000 for 6 months (or 6 monthly payments of $2,100)',
        paymentPlanCount: 6,
        pifDiscountPercent: 10,
      },
      guaranteeOrRisk: 'If you don\'t lose 20 lbs in the first 90 days while following the protocol, I work with you free until you do.',
      guaranteeTimeframe: 'first 90 days of the program',
      fastActionBonusDeadline: '72 hours from application call',
      scarcityElement: 'Only 12 active clients at a time — enrollment opens only when an existing client graduates.',
      programDuration: '6 months',
      programIncludes: 'Custom training program, nutrition protocol, weekly video check-ins, private Slack access, biweekly 1-on-1 calls, hotel/travel protocols.',
      transformation: 'From burnt-out executive who avoids the mirror to a strong, lean, high-energy leader who trains on his own terms.',
      uniqueMechanism: 'The Performance Stack — a 3-layer system that syncs training, nutrition, and recovery to the rhythm of a 60-hour work week.',
      firstResultTimeframe: 'within the first 3 weeks — clients drop 5-8 lbs and feel noticeably stronger before month 1 ends',
      targetClientMonthlyRevenue: 'No revenue target (fitness niche). Typical client result: 25-45 lbs lost and strength baseline doubled by month 6.',
      leadMagnetName: 'The Executive\'s 15-Minute Workout',
      leadMagnetType: 'pdf-guide',
      ctaType: 'application',
      ctaKeyword: '',
      revenuePerClient: '$12000',

      // Step 6: Results
      caseStudies: [
        {
          clientName: 'Dan M.',
          businessType: 'SaaS CEO',
          beforeState: 'Burned out, 42 lbs over target, hadn\'t trained in 3 years',
          intervention: '6-month Executive Athlete Program',
          result: 'Lost 42 lbs, squats 2x bodyweight, travels 2 weeks/month and stays on track',
          timeframe: '6 months',
          quote: 'Marcus is the only trainer who actually gets what my life is like.',
        },
        {
          clientName: 'Rick P.',
          businessType: 'private equity partner',
          beforeState: 'Prediabetic A1C of 6.2',
          intervention: '6-month program + nutrition overhaul',
          result: 'A1C dropped to 5.4, lost 28 lbs',
          timeframe: '6 months',
          quote: 'My doctor couldn\'t believe the numbers.',
        },
      ],
      trackRecord: {
        yearsInIndustry: '11 years',
        clientsHelped: '340 clients',
        revenueGenerated: '',
        certifications: 'NASM CPT, Precision Nutrition L1',
      },
      objectionRebuttals: [],
      clientSuccessRate: {
        clientsAchievedResult: 52,
        totalClientsInProgram: 60,
      },

      // Step 7: Final Details
      expertise: ['executive fitness', 'at-home training', 'travel nutrition'],
      brandVoice: 'tactical',
      contentCadence: 'weekly',
      voiceNotes: 'Direct, no-BS, tactical. Never uses hype words like "incredible" or "amazing".',
      applicationUrl: 'https://reedperformance.co/apply',
      offerDetailsUrl: 'https://reedperformance.co/program',
      leadMagnetUrl: 'https://reedperformance.co/15-minute-workout',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 2. BUSINESS/MINDSET COACH — ABSTRACT NICHE (generic metaphor risk)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'business-abstract',
    label: 'Sarah Chen — Business/Mindset Coach (abstract niche)',
    niche: 'mindset coaching for female entrepreneurs',
    answers: {
      clientName: 'Sarah Chen',
      businessName: 'Unbound Leadership',
      elevatorPitch: 'I help female founders rewrite the inner narratives that keep them stuck below six figures.',
      coachingYears: '7 years coaching',
      totalClientsCoached: '180 one-on-one clients',
      businessesBuiltList: 'Grew a consulting business from $0 to $420K in 3 years before pivoting to coaching.',
      positionsHeld: 'Former product manager at Shopify (2016-2019)',
      certifications: 'ICF-certified, trained in Internal Family Systems',
      mediaAndStages: 'Featured on the Unapologetic Business podcast',
      notableAssociations: '',
      twelveMonthVision: 'Build a signature group program with 100 members.',

      upbringing: 'Born in Taiwan, immigrated to Canada at age 8.',
      parentInfluence: 'My parents drilled into me that achievement = worthiness.',
      coachingLineage: 'Trained under Dr. Karen Hill in IFS and somatic work.',
      firstBusiness: 'Product consulting practice in Toronto',
      storyBeforeState: 'At 33 I had a "successful" consulting business making $400K, but I was working 70-hour weeks, drinking to sleep, and silently resenting every client who asked for another revision.',
      storyTurningPoint: 'My therapist asked me, "What would you do if you believed you were already enough?" I didn\'t have an answer, and that terrified me.',
      storyAfterState: 'I spent 2 years in deep inner work, got ICF-certified, and pivoted the business to coaching women through the exact patterns I\'d been stuck in.',
      whyDoThis: 'Because the hustle playbook is killing a generation of female founders and no one is telling them the truth about why.',
      personalHobbies: ['pottery', 'hiking', 'tarot'],
      personalLife: 'Lives in Toronto with partner and a border collie.',
      storyFacts: 'Shopify PM 2016-2019. Consulting business 2019-2022, peaked at $420K. ICF certified 2021. Coaching business launched 2022. 180 clients total.',

      niche: 'Mindset coaching for female founders with 6-figure businesses',
      targetAudience: 'Women founders age 30-45 running service businesses making $150K-$500K who feel trapped by their own success.',
      bestClientEver: 'A marketing agency founder who tripled her prices in 4 months after identity work.',
      topComplaints: 'No time for anything but client work. Can\'t charge what she\'s worth.',
      unwantedFeelings: 'Resentful, exhausted, invisible, lonely at the top.',
      topDesires: 'Permission to slow down. To be seen. To raise prices without guilt.',
      desiredFeelings: 'Spacious, grounded, self-trusting, proud.',
      idealClientCurrentMethods: 'Reads business books. Joins Masterminds. Follows mindset coaches on Instagram. Journals sporadically.',
      whyCurrentMethodFails: 'Strategies at the behavior layer when the problem is identity and nervous system.',
      aspiringIdentity: 'The Sovereign CEO — a woman who runs her business from self-trust instead of self-abandonment.',
      problemSolved: 'Six-figure female founders who hit an income ceiling because of patterns they can\'t see.',
      commonObjections: [
        'Mindset work feels too woo',
        'I need tactics, not therapy',
        'I don\'t have time for another program',
      ],
      salesApproach: 'discovery-call',
      deliveryModel: 'hybrid',
      idealClientCurrentRevenue: '$150K-$500K/year',
      idealClientStuckDuration: '2-4 years plateaued',
      monthlyActionCost: '~$8,000/month in underpricing alone (charging half of competitors) plus 15-20 hours/week trapped in client work that should be delegated.',

      clientExcuse: 'I just need to be more disciplined.',
      clientSecretDesire: 'Take a month off without the business collapsing.',
      clientFalseProblem: 'I need better marketing.',
      clientRealProblem: 'Self-worth tied to productivity.',
      clientSecretFear: 'If I stop hustling, I\'ll discover I\'m not actually that talented.',
      clientAngerTrigger: 'Husband asking, "Why are you working on Sunday again?"',
      clientBlameTarget: 'Every coach who told her to just "work harder on her mindset."',
      clientGuiltShame: 'Snapping at her kids because of a client email.',
      clientDailyReminder: 'The 47 unread messages in her Slack at 10pm.',
      clientInactionConsequence: 'Divorce. Burnout at 45. Selling a business built on a crumbling inner foundation.',

      offerName: 'The Sovereign CEO',
      programPhases: [
        { phaseName: 'Excavate', description: '4 weeks uncovering the hidden operating system', outcome: 'Clarity on the root patterns' },
        { phaseName: 'Integrate', description: '8 weeks of somatic + IFS practice', outcome: 'New default nervous system state' },
        { phaseName: 'Embody', description: '12 weeks applying it to real business decisions', outcome: 'Lived evidence of the new identity' },
      ],
      doneForYou: 'Weekly 1-on-1 calls, monthly group sessions, voxer access between sessions.',
      taughtSkills: 'IFS self-leadership, somatic regulation, sovereignty frameworks.',
      billboardResult: 'Run a 7-figure business from self-trust instead of self-abandonment.',
      bonuses: 'Private Circle community, quarterly retreats.',
      clientCapacity: '20 active clients',
      pricing: {
        totalUSD: 18000,
        billingType: 'installments' as const,
        displayString: '$18,000 for 6 months (or 6 monthly payments of $3,200)',
        paymentPlanCount: 6,
        pifDiscountPercent: 10,
      },
      guaranteeOrRisk: 'If after 60 days you don\'t feel a meaningful shift, full refund.',
      guaranteeTimeframe: 'first 60 days of the program',
      fastActionBonusDeadline: '48 hours from discovery call',
      scarcityElement: 'Cohort caps at 20 active clients. New cohort opens quarterly — once full, the next doors open 3 months out.',
      programDuration: '6 months',
      programIncludes: 'Weekly 1-on-1 sessions, monthly group calls, Voxer access, Circle community, quarterly retreats.',
      transformation: 'From resentful high-achiever who can\'t stop to a sovereign CEO who leads from fullness.',
      uniqueMechanism: 'The Sovereignty Stack — three-layer integration of IFS parts work, somatic regulation, and business operating systems.',
      firstResultTimeframe: 'by the end of week 4 — clients report their first real "permission to slow down" moment, usually a full day off without guilt',
      targetClientMonthlyRevenue: '$35K-$80K/month at the end of the program (up from $12K-$40K/month at intake), with 30-40% fewer working hours',
      leadMagnetName: 'The Sovereign CEO Audit',
      leadMagnetType: 'quiz',
      ctaType: 'booking',
      ctaKeyword: '',
      revenuePerClient: '$18000',

      caseStudies: [
        {
          clientName: 'Priya R.',
          businessType: 'marketing agency',
          beforeState: 'Making $180K, burnt out, charging half of competitors',
          intervention: '6-month Sovereign CEO program',
          result: 'Tripled prices, dropped 70% of clients, now $420K/year with half the workload',
          timeframe: '7 months',
          quote: 'I finally stopped feeling guilty for charging what I\'m worth.',
        },
      ],
      trackRecord: {
        yearsInIndustry: '7 years',
        clientsHelped: '180 clients',
        certifications: 'ICF ACC certified',
      },
      objectionRebuttals: [],
      clientSuccessRate: {
        clientsAchievedResult: 28,
        totalClientsInProgram: 40,
      },

      expertise: ['somatic leadership', 'IFS for founders', 'pricing psychology'],
      brandVoice: 'authoritative',
      contentCadence: 'weekly',
      voiceNotes: 'Warm but direct. Names the uncomfortable truths. No toxic positivity.',
      applicationUrl: '',
      offerDetailsUrl: 'https://unboundleadership.co/sovereign-ceo',
      leadMagnetUrl: 'https://unboundleadership.co/audit',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 3. RELATIONSHIP COACH — DENSE INPUT (false-positive stress test)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'relationship-dense',
    label: 'David Alvarez — Relationship Coach (dense input)',
    niche: 'post-divorce dating coaching for men',
    answers: {
      clientName: 'David Alvarez',
      businessName: 'Second Act Dating',
      elevatorPitch: 'I help divorced men over 45 find a loving relationship without repeating the patterns that broke the first one.',
      coachingYears: '9 years coaching',
      totalClientsCoached: '420 men',
      businessesBuiltList: 'Built and sold a dating site called MatchAgain in 2019 for $1.2M. Co-founded the Second Chance Summit (annual event, 800 attendees).',
      positionsHeld: 'Board member of the Divorce Recovery Network',
      certifications: 'MA in Clinical Psychology (NYU 2010), Gottman Method Level 2',
      mediaAndStages: 'TEDx Charlotte 2021, Men\'s Health Magazine feature (March 2022), 40+ podcast appearances.',
      notableAssociations: 'Gottman Institute certified practitioner',
      twelveMonthVision: 'Grow the signature program to 200 active clients.',

      upbringing: 'Raised in the Bronx by Dominican parents.',
      parentInfluence: 'My dad walked out when I was 8. My mom raised us on her own.',
      coachingLineage: 'Studied under Dr. John Gottman at his institute in Seattle (2016-2018).',
      firstBusiness: 'Private therapy practice in Charlotte NC',
      storyBeforeState: 'After my own divorce in 2014, I spent 18 months dating badly. I was angry, distrustful, and kept attracting women who reminded me of my ex. I was 38 years old, making $180K in a private therapy practice, and still sleeping on a mattress on the floor of a rental.',
      storyTurningPoint: 'My mentor told me: "You\'re not dating to find a partner. You\'re dating to prove your ex wrong. That\'s why every relationship fails." It broke me open.',
      storyAfterState: 'I did 2 years of my own therapy, closed the private practice, and launched a dating program specifically for men coming out of divorce. Today I have a 3000-person community and run 6 retreats per year.',
      whyDoThis: 'Because my father never came back for me, and I refuse to let another man disappear from his own life.',
      personalHobbies: ['bachata', 'Brazilian jiu-jitsu', 'cooking'],
      personalLife: 'Remarried in 2021 to a woman I met in the program community. Two daughters, ages 14 and 11.',
      storyFacts: 'Divorced in 2014. MA Psychology NYU 2010. Gottman Level 2 certified 2018. Built MatchAgain 2017-2019, sold for $1.2M. Second Act Dating launched 2019. 420 clients coached. Remarried 2021.',

      niche: 'Post-divorce dating coaching for men 45+',
      targetAudience: 'Divorced men age 45-60 who make $200K+ and have been single for 1-4 years with no traction on dating apps.',
      bestClientEver: 'A surgeon who had been divorced 3 years, did the 6-month program, and got engaged to a woman he met at one of our retreats.',
      topComplaints: 'Dating apps are broken. Everyone ghosts. Can\'t tell who\'s serious.',
      unwantedFeelings: 'Invisible, angry, defeated, suspicious of every woman\'s motives.',
      topDesires: 'A real partner who sees him. To stop feeling like dating is a math problem. To trust again.',
      desiredFeelings: 'Hopeful, selective, confident, at peace with his history.',
      idealClientCurrentMethods: 'Matches on Bumble and Hinge, sends 30 messages a week, goes on 2 first dates a month that never go anywhere.',
      whyCurrentMethodFails: 'Dating from wound, not from wholeness. Attracts women looking for what he\'s looking to escape.',
      aspiringIdentity: 'The Emotionally Intelligent Second-Act Man — a guy who attracts the right women because he finally knows who he is.',
      problemSolved: 'Divorced men over 45 who keep dating the same type of woman and ending up in the same type of relationship.',
      commonObjections: [
        'Dating coaches are for 25-year-olds',
        'I don\'t need therapy — I need more matches',
        'Group programs won\'t work for me',
      ],
      salesApproach: 'discovery-call',
      deliveryModel: 'group-program',
      idealClientCurrentRevenue: '$200K-$1M/year',
      idealClientStuckDuration: '2-4 years dating unsuccessfully',
      monthlyActionCost: 'Roughly $400-600/month burned on dating apps, premium subscriptions, and therapy — plus the emotional cost of another year dating from the wound instead of from wholeness.',

      clientExcuse: 'I\'ll start dating again once work slows down.',
      clientSecretDesire: 'To be chosen, not settled for.',
      clientFalseProblem: 'I just need better matches.',
      clientRealProblem: 'Dating from the wound of his divorce.',
      clientSecretFear: 'That he\'ll die alone in his apartment.',
      clientAngerTrigger: 'His ex posting photos with her new partner.',
      clientBlameTarget: 'Every dating app and every woman who ghosted him.',
      clientGuiltShame: 'That his kids see him as a broken man.',
      clientDailyReminder: 'His empty bed at 6am.',
      clientInactionConsequence: 'Dying alone. Becoming his father. His kids never seeing him in a healthy relationship.',

      offerName: 'The Second Act Method',
      programPhases: [
        { phaseName: 'Grounding', description: '4 weeks of post-divorce identity work', outcome: 'Emotional baseline reset' },
        { phaseName: 'Rebuilding', description: '8 weeks of attachment pattern work', outcome: 'New dating frame established' },
        { phaseName: 'Attracting', description: '12 weeks of real-world dating practice', outcome: 'Consistent dates with right-fit women' },
      ],
      doneForYou: 'Weekly group coaching calls, monthly 1-on-1s, profile audits, text review thread.',
      taughtSkills: 'Gottman-based attachment frameworks, dating app optimization, first-date protocols, handling triggers.',
      billboardResult: 'Find a partner who chooses you without settling or performing.',
      bonuses: 'Access to the 3,000-person Brotherhood community, quarterly weekend retreats.',
      clientCapacity: '40 active members',
      pricing: {
        totalUSD: 9500,
        billingType: 'installments' as const,
        displayString: '$9,500 for 6 months (or 3 payments of $3,300)',
        paymentPlanCount: 3,
        pifDiscountPercent: 5,
      },
      guaranteeOrRisk: '12-month extension if you don\'t have three meaningful dates per month by month 4.',
      guaranteeTimeframe: 'by end of month 4 in the program',
      fastActionBonusDeadline: '48 hours from discovery call',
      scarcityElement: 'Cohort caps at 40 active members; doors open once per quarter aligned with the Brotherhood retreat schedule.',
      programDuration: '6 months',
      programIncludes: 'Weekly group coaching calls, monthly 1-on-1, Brotherhood community, quarterly retreats, profile + text review, framework library.',
      transformation: 'From a divorced man who dates from the wound to a Second-Act Man who chooses from wholeness.',
      uniqueMechanism: 'The Second Act Method — a 3-phase Gottman-based protocol for rebuilding attachment capacity after divorce.',
      firstResultTimeframe: 'within the first 30 days — most men report 2-3 meaningful first dates and a noticeable shift in how they show up emotionally',
      targetClientMonthlyRevenue: 'No revenue target (relationship niche). Typical milestone: 3+ meaningful dates per month and an age-appropriate partner within 6-9 months.',
      leadMagnetName: 'The Second-Act Dating Audit',
      leadMagnetType: 'quiz',
      ctaType: 'booking',
      ctaKeyword: '',
      revenuePerClient: '$9500',

      caseStudies: [
        {
          clientName: 'Dr. James K.',
          businessType: 'cardiac surgeon',
          beforeState: 'Divorced 3 years, 0 second dates in 18 months',
          intervention: '6-month Second Act Method',
          result: 'Engaged to a woman he met at our November retreat',
          timeframe: '8 months',
          quote: 'The only reason I\'m not alone at 52 is this program.',
        },
        {
          clientName: 'Carlos M.',
          businessType: 'restaurant owner',
          beforeState: 'Divorced 2 years, drinking too much, dating women 15 years younger',
          intervention: '6-month program + 1 retreat',
          result: 'Sober, dating an age-appropriate partner for 9 months and counting',
          timeframe: '10 months',
          quote: 'I stopped running from myself.',
        },
        {
          clientName: 'Mike D.',
          businessType: 'tech founder',
          beforeState: 'Divorced 18 months, avoided dating entirely',
          intervention: 'Full program + 2 retreats',
          result: 'In a committed relationship with someone he calls "the right person at the right time"',
          timeframe: '11 months',
          quote: 'I wasn\'t broken. I was healing.',
        },
      ],
      trackRecord: {
        yearsInIndustry: '9 years',
        clientsHelped: '420 men',
        revenueGenerated: 'MatchAgain sold for $1.2M in 2019',
        certifications: 'MA Psychology NYU, Gottman Method Level 2',
        speakingEngagements: 'TEDx Charlotte 2021',
        mediaAppearances: 'Men\'s Health Magazine March 2022, 40+ podcasts',
      },
      objectionRebuttals: [],
      clientSuccessRate: {
        clientsAchievedResult: 63,
        totalClientsInProgram: 80,
      },

      expertise: ['post-divorce recovery', 'attachment theory', 'dating app strategy'],
      brandVoice: 'authoritative',
      contentCadence: 'weekly',
      voiceNotes: 'Warm, grounded, unflinching. Speaks man-to-man without cliches.',
      applicationUrl: '',
      offerDetailsUrl: 'https://secondactdating.com/program',
      leadMagnetUrl: 'https://secondactdating.com/audit',
    },
  },
]
