/**
 * Post-Generation Fact Scanner
 *
 * Deterministic verification pass that runs after the LLM generates content.
 * Extracts every number, money amount, duration, and proper noun from the output,
 * then checks each one against the fact allowlist (built from questionnaire answers).
 *
 * Anything not in the allowlist is flagged as a potential hallucination.
 *
 * This is the primary defense against the "math on client numbers" and "paraphrased
 * exact phrases" hallucination patterns — things the LLM QA reviewer has blind
 * spots for because it shares the generator's biases.
 */

import { FactAllowlist, normalizeNumber, normalizeDuration } from './fact-allowlist'

export type HallucinationType = 'money' | 'duration' | 'number' | 'proper_noun'
export type HallucinationSeverity = 'critical' | 'warning'

export interface Hallucination {
  type: HallucinationType
  value: string
  evidence: string  // ~80 chars of surrounding text
  severity: HallucinationSeverity
  index: number     // Start index of `value` within the (cleaned) content — used for auto-redaction
  length: number    // Length of the matched span
}

export interface ScanResult {
  hallucinations: Hallucination[]
  scanned: number      // Total claims extracted from content
  verified: number     // How many matched the allowlist
}

// Content sections that are template scaffolding, not claims about the coach
const PLACEHOLDER_PATTERNS = [
  /\[COACH:[^\]]*\]/gi,
  /\[INSERT[^\]]*\]/gi,
  /\[DATA NOT PROVIDED[^\]]*\]/gi,
  /\[ADD:[^\]]*\]/gi,
  /\{\{[^}]+\}\}/g,
]

// Proper nouns that are common vocabulary, not real-world entities
const PROPER_NOUN_ALLOWLIST = new Set([
  'United States', 'New York', 'Los Angeles', 'North America', 'South America',
  'North Star', 'Easy Street', 'Main Street', 'Silicon Valley',
  'Super Bowl', 'Wall Street',
  // Template-structural labels that appear in case-study tables / section headers
  'What We Did', 'What We', 'Before State', 'After State', 'Hell Island', 'Heaven Island',
  'Pain Zone', 'Proof Stack', 'Mission Statement', 'Human Bio', 'Two Identities',
  'Belief Shift', 'Belief Shifts', 'Belief Map', 'Belief Breakthrough', 'Sovereignty Stack',
  'Content Playbook', 'Content Angle', 'Lead Magnet', 'Sales Script', 'Sales Call', 'Sales Letter',
  'Authority Reference', 'Authority Amplifier', 'Core Belief', 'Money Messaging',
  'Mind Shift', 'Mind Shift Method', 'Conversion Code', 'Case Study', 'Case Studies',
  'Client Name', 'Client Results', 'Key Facts', 'Track Record', 'Executive Athlete',
  'Universal Analogy', 'Internal Case', 'External Case', 'Cross Domain', 'Cross-Domain',
  // Ordinal-numbered structural labels (Phase One, Step Two, etc.)
  'Phase One', 'Phase Two', 'Phase Three', 'Phase Four', 'Phase Five',
  'Step One', 'Step Two', 'Step Three',
  'Bold Guarantee', 'Balanced Guarantee', 'Conservative Guarantee',
  'Fast Action', 'Option One', 'Option Two', 'Option Three',
])

// Structural template output — ordinal or phase/step/version labels used as section headers.
// These are generated by templates, not hallucinated proper nouns.
const STRUCTURAL_LABEL_REGEX = /^(Phase|Step|Version|Part|Section|Module|Week|Day|Option|Stage)\s+(One|Two|Three|Four|Five|Six|Seven|Eight|Nine|Ten|First|Second|Third|Final|Last)\b/i

/**
 * Narrative/hypothetical framing — if a number is inside a section labeled as prospect
 * psychology, avatar description, pain zone, etc., the number is narrative framing about
 * the prospect (not a claim about the coach) and should be demoted from critical to warning.
 */
const HYPOTHETICAL_MARKERS = [
  'hell island', 'heaven island', 'pain zone', 'possibility', 'avatar',
  'prospect', 'ideal client', 'target audience',
  'emotional trigger', 'false belief', 'secret fear', 'secret desire',
  'hypothetical', 'imagine', 'suppose', 'for example',
  'daily reminder', 'daily observation', 'common objection',
  'inner voice', 'what they think', 'what they say', 'what they feel',
]

function isHypotheticalContext(evidence: string): boolean {
  const lower = evidence.toLowerCase()
  if (HYPOTHETICAL_MARKERS.some(m => lower.includes(m))) return true
  // Second-person narration about the prospect: "You spend...", "You make..."
  if (/\byou\s+(spend|make|earn|have|lose|waste|pay|work|feel|think)/i.test(evidence)) return true
  // Direct quote markers (common in prospect-voice content)
  if (/["\u201c]\s*(i|my|me)\s/i.test(evidence)) return true
  return false
}

// Numbers that are universal and shouldn't be flagged (year markers, etc.)
const NUMBER_ALLOWLIST = new Set([
  '100', // "100% guarantee"
  '24', '12', '365',  // time-related universals
  '1000',  // common in "1,000 clients served"-style fill-in-the-blanks
])

const NUMBER_REGEX = /\b(\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?\b/g
// KkMm unit must be followed by a non-letter — otherwise "$500 monthly" swallows "m" as millions
const MONEY_REGEX = /\$\s?(\d+(?:,\d{3})*(?:\.\d+)?)\s?([KkMm](?![a-zA-Z]))?/g
const DURATION_REGEX = /\b(\d+)\s*(year|years|yr|yrs|month|months|mo|week|weeks|wk|wks|day|days|decade|decades)\b/gi
const PROPER_NOUN_REGEX = /\b[A-Z][a-z]+(?:\s+(?:of|the|and|&)?\s*[A-Z][a-z]+)+\b/g

/**
 * Strip template placeholders so we don't flag `[COACH: Insert number]` as a hallucination.
 * Replaces each matched placeholder with a run of spaces of EQUAL length so that indices
 * inside `cleaned` still line up with indices in the original `content` — critical for
 * auto-redaction later.
 */
function stripPlaceholders(content: string): string {
  let cleaned = content
  for (const pattern of PLACEHOLDER_PATTERNS) {
    cleaned = cleaned.replace(pattern, match => ' '.repeat(match.length))
  }
  return cleaned
}

function evidenceAround(content: string, index: number, matchLength: number): string {
  const start = Math.max(0, index - 40)
  const end = Math.min(content.length, index + matchLength + 40)
  return content.slice(start, end).replace(/\s+/g, ' ').trim()
}

export function scanForHallucinations(
  content: string,
  allowlist: FactAllowlist
): ScanResult {
  const cleaned = stripPlaceholders(content)
  const result: ScanResult = { hallucinations: [], scanned: 0, verified: 0 }

  // Track money spans so we don't double-count the digits inside "$5,000" as a bare number
  const moneySpans: Array<[number, number]> = []

  // ── Money ───────────────────────────────────────────────────────────────
  for (const m of cleaned.matchAll(MONEY_REGEX)) {
    if (m.index === undefined) continue
    result.scanned++
    moneySpans.push([m.index, m.index + m[0].length])

    const digits = m[1]
    const unit = m[2]
    const normalized = normalizeNumber(digits + (unit || ''))

    if (allowlist.money.has(normalized) || allowlist.numbers.has(normalized)) {
      result.verified++
      continue
    }

    const evidence = evidenceAround(cleaned, m.index, m[0].length)
    result.hallucinations.push({
      type: 'money',
      value: m[0],
      evidence,
      severity: isHypotheticalContext(evidence) ? 'warning' : 'critical',
      index: m.index,
      length: m[0].length,
    })
  }

  // ── Durations ───────────────────────────────────────────────────────────
  for (const m of cleaned.matchAll(DURATION_REGEX)) {
    if (m.index === undefined) continue
    result.scanned++
    const normalized = normalizeDuration(m[0])

    if (allowlist.durations.has(normalized)) {
      result.verified++
      continue
    }

    const evidence = evidenceAround(cleaned, m.index, m[0].length)
    result.hallucinations.push({
      type: 'duration',
      value: m[0],
      evidence,
      severity: isHypotheticalContext(evidence) ? 'warning' : 'critical',
      index: m.index,
      length: m[0].length,
    })
  }

  // ── Plain numbers (skip anything inside a money span) ───────────────────
  for (const m of cleaned.matchAll(NUMBER_REGEX)) {
    if (m.index === undefined) continue
    const inMoney = moneySpans.some(([s, e]) => m.index! >= s && m.index! < e)
    if (inMoney) continue

    const normalized = normalizeNumber(m[0])
    const asInt = parseInt(normalized, 10)
    if (isNaN(asInt) || asInt < 10) continue  // Skip single digits — too noisy

    result.scanned++
    if (NUMBER_ALLOWLIST.has(normalized) || allowlist.numbers.has(normalized)) {
      result.verified++
      continue
    }

    result.hallucinations.push({
      type: 'number',
      value: m[0],
      evidence: evidenceAround(cleaned, m.index, m[0].length),
      severity: 'warning',  // Plain numbers are lower signal than money/durations
      index: m.index,
      length: m[0].length,
    })
  }

  // ── Proper nouns ────────────────────────────────────────────────────────
  for (const m of cleaned.matchAll(PROPER_NOUN_REGEX)) {
    if (m.index === undefined) continue
    const value = m[0]
    if (PROPER_NOUN_ALLOWLIST.has(value)) continue
    if (STRUCTURAL_LABEL_REGEX.test(value)) continue

    result.scanned++
    if (allowlist.properNouns.has(value)) {
      result.verified++
      continue
    }

    // Substring fallback: match is OK if any portion appears in raw answers text
    // (catches cases where the allowlist missed a name but it IS in the input)
    if (allowlist.rawText.includes(value.toLowerCase())) {
      result.verified++
      continue
    }

    result.hallucinations.push({
      type: 'proper_noun',
      value,
      evidence: evidenceAround(cleaned, m.index, value.length),
      severity: 'warning',  // Could be a known public figure mentioned for framing
      index: m.index,
      length: value.length,
    })
  }

  return result
}

// ─────────────────────────────────────────────────────────────────────────
// Auto-redactor — replaces hallucinated spans with [COACH: Insert ...]
// ─────────────────────────────────────────────────────────────────────────

export interface RedactionResult {
  content: string        // Content with hallucinated spans replaced
  redacted: number       // How many spans were replaced
  redactedValues: string[]  // The exact values that got redacted (for logging / reporting)
}

// Replacement strings for hallucinated spans. Semantic labels tell coaches
// exactly what data category is missing (vs. bare `___` which is opaque).
const REDACTION_PLACEHOLDER: Record<HallucinationType, string> = {
  money: '[ADD: your $ figure]',
  duration: '[ADD: your timeframe]',
  number: '[ADD: your number]',
  proper_noun: '[ADD: name/program]',
}

/**
 * Replace every hallucination flagged with the given severity (default 'critical') with a
 * `[COACH: Insert ...]` placeholder. Processes hits in reverse index order so earlier
 * replacements don't shift later indices.
 *
 * This is the "strong fix" — the scanner stops being just an alarm and becomes an editor.
 * Works on ALL templates uniformly because it operates on the output, not the prompt.
 */
export function redactHallucinations(
  content: string,
  hallucinations: Hallucination[],
  opts: { severity?: HallucinationSeverity } = {},
): RedactionResult {
  const severity = opts.severity ?? 'critical'
  const targets = hallucinations
    .filter(h => h.severity === severity)
    .sort((a, b) => b.index - a.index)  // reverse order so index math stays valid

  if (targets.length === 0) {
    return { content, redacted: 0, redactedValues: [] }
  }

  let out = content
  const values: string[] = []

  for (const h of targets) {
    // Safety check: confirm the span in `content` still matches what we expect. If it
    // doesn't (e.g. because stripPlaceholders shifted something we missed), skip it —
    // redacting the wrong span is worse than leaving the hallucination in.
    const actual = out.slice(h.index, h.index + h.length)
    if (actual !== h.value) continue

    values.push(h.value)
    out = out.slice(0, h.index) + REDACTION_PLACEHOLDER[h.type] + out.slice(h.index + h.length)
  }

  return { content: out, redacted: values.length, redactedValues: values }
}
